### ISSUE TITLE
Cf Lingua Franca

### ISSUE THREAD

**Issue by edwardalee** [microsoft/AccessorFramework#4]
A refinement of accessors is Lingua Franca (see https://github.com/icyphy/lingua-franca ) that you may want to check out. There is a C target and an Accessors target, with the C target being better developed and more mature. Creating a C++ target would be relatively easy, I think.

**Comment by bryan-hicks** [comment]
LF looks like a promising project; the clarity and conciseness of the syntax could save development time, and the multi-language support could be useful for leveraging language-specific characteristics for a given scenario. It looks like there is now a C++ target as well. It may be too late to migrate projects that are already in motion, but I'd strongly consider using it as a platform for new projects.
